<?php

namespace Database\Seeders;

use App\Models\FilterTemplate;
use App\Models\Template;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Template::$isSeederRunning = true;

        $templates = [
            [
                'title' => 'Gold leaf',
                'title_ar' => 'أوراق الذهب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0001',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Gold leaf - 1.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Gold Stars',
                'title_ar' => 'النجوم الذهبية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0002',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Gold Stars - 2.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Elegant Triangle',
                'title_ar' => 'المثلث الأنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0003',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Elegant Triangle - 3.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Gold flowers',
                'title_ar' => 'زهور ذهبية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0004',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Gold flowers - 4.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Silver Leaf',
                'title_ar' => 'ورقة فضية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0005',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Silver Leaf - 5.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Elegant Gold and Black',
                'title_ar' => 'ذهبي وأسود أنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0129',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Elegant Gold and Black - 6.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Black Ornament',
                'title_ar' => 'زخرفة سوداء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0130',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Black Ornament -  7.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Elegant Glitter',
                'title_ar' => 'بريق أنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0131',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding - Elegant Glitter - 8.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Mysterious navy blue',
                'title_ar' => 'الأزرق الداكن الغامض',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0132',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - Mysterious navy blue - 9.png',
                'filter_id' => '1',
            ],
            [
                'title' => 'White Ornament',
                'title_ar' => 'زخرفة بيضاء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0133',
                'category_id' => '1',
                'image' => '/templates_image/Wedding Men/Wedding Men - White Ornament - 10 .png',
                'filter_id' => '1',
            ],
            [
                'title' => 'Lovely blossom plum',
                'title_ar' => 'زهر البرقوق الجميل',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0006',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Lovely blossom plum  - 1.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Shy love',
                'title_ar' => 'حب خجول',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0007',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman -Shy love - 2.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Warm winter',
                'title_ar' => 'الشتاء دافئ',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0008',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - warm winter - 3.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Blue Jasmine',
                'title_ar' => 'الياسمين الأزرق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0009',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Blue Jasmine - 4.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Sultan',
                'title_ar' => 'سلطان',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0010',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Sultan - 5.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'happy sunset',
                'title_ar' => 'غروب الشمس سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0134',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - happy sunset - 6.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Crystal night',
                'title_ar' => 'ليلة كريستال',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0135',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Crystal night - 7.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Magnolia',
                'title_ar' => 'ماغنوليا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0136',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Magnolia - 8.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Dream',
                'title_ar' => 'حلم',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0137',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding - Dream - 9.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'passion',
                'title_ar' => 'عاطفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0138',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - passion - 10.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Colorful stories',
                'title_ar' => 'قصص ملونة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0139',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding Woman - Colorful stories - 11.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Roze',
                'title_ar' => 'روز',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0140',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Roze - 12.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Passion story',
                'title_ar' => 'قصة العاطفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0141',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Passion story - 13.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'first dance',
                'title_ar' => 'أول رقصة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0142',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - first dance - 14.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Bordeaux',
                'title_ar' => 'بوردو',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0143',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Bordeaux - 15.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Spring love',
                'title_ar' => 'ربيع الحب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0144',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding Woman - Spring love - 16.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Royal',
                'title_ar' => 'رويال',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0145',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding Woman - Royal - 17.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'royal blue',
                'title_ar' => 'الأزرق الملكي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0146',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - royal blue - 18.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Happy magnolia',
                'title_ar' => 'ماغنوليا سعيدة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0147',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Happy magnolia - 19.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Royal night',
                'title_ar' => 'ليلة ملكية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0148',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Royal night  - 20.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Hydrangea macrophylla',
                'title_ar' => 'الكوبية ماكروفيلا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0149',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Hydrangea macrophylla - 21.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'happy green',
                'title_ar' => 'أخضر سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0150',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - happy green - 22.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'elegant pink',
                'title_ar' => 'الوردي الأنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0151',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - elegant pink - 23.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Orchid',
                'title_ar' => 'زهرة الأوركيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0152',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding Woman - Orchid - 24.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Summer',
                'title_ar' => 'صيف',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0153',
                'category_id' => '1',
                'image' => '/templates_image/Wedding woman/Wedding woman - Summer - 25.png',
                'filter_id' => '2',
            ],
            [
                'title' => 'Dahlia',
                'title_ar' => 'الداليا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0011',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Dahlia -1 .png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Masterpiece',
                'title_ar' => 'تحفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0012',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Masterpiece  - 2.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Black Roze',
                'title_ar' => 'بلاك روز',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0013',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Black Roze - 3.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Dreamy Gold',
                'title_ar' => 'حالمة الذهب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0014',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Dreamy Gold - 4.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Imaginary Love',
                'title_ar' => 'الحب الخيالي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0015',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Imaginary Love - 5.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Gold Flowers',
                'title_ar' => 'زهور الذهب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0154',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Gold Flowers - 6.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Golden Leaf',
                'title_ar' => 'الورقة الذهبية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0155',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Golden Leaf - 7.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Golden Mandala',
                'title_ar' => 'ماندالا الذهبية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0156',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Golden Mandala - 8.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Elegant Mandala',
                'title_ar' => 'ماندالا الأنيقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0157',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Elegant Mandala - 9.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Elegant Gold',
                'title_ar' => 'الذهب الأنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0158',
                'category_id' => '1',
                'image' => '/templates_image/Engagement Men/Engagment  Men - Elagant Gold - 10.png',
                'filter_id' => '3',
            ],
            [
                'title' => 'Warm green',
                'title_ar' => 'أخضر دافئ',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0016',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Warm green - 1 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Autumn leaf',
                'title_ar' => 'ورقة الخريف',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0017',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Autumn leaf - 2 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Cherry love',
                'title_ar' => 'الكرز الحب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0018',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman -Cherry love - 3 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'lovely pink',
                'title_ar' => 'وردي جميل',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0019',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - lovely pink - 4 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Love Gate',
                'title_ar' => 'بوابة الحب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0020',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Love Gate - 5 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Colorful leaves',
                'title_ar' => 'أوراق ملونة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0159',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman -Colorful leaves - 6 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Plum blossom',
                'title_ar' => 'زهر البرقوق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0160',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Plum blossom - 7 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Blue Roze',
                'title_ar' => 'بلو روز',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0161',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman -Blue Roze - 8.png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Spring',
                'title_ar' => 'ربيع',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0162',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Spring - 9 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Spring warmth',
                'title_ar' => 'دفء الربيع',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0163',
                'category_id' => '1',
                'image' => '/templates_image/Engagement woman/Engagement woman - Spring warmth - 10 .png',
                'filter_id' => '4',
            ],
            [
                'title' => 'Soft Ornaments',
                'title_ar' => 'الحلي الناعمة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0021',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Soft Ornaments - 1 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Beautiful hands',
                'title_ar' => 'أيدي جميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0022',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Beautiful hands - 2 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Delicate decoration',
                'title_ar' => 'زخرفة حساسة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0023',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Delicate decoration - 3 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Wave of love',
                'title_ar' => 'موجة الحب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0024',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Wave of love - 4 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Rose decoration',
                'title_ar' => 'زخرفة الورد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0025',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Rose decoration - 5 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Dreamy night',
                'title_ar' => 'ليلة حالمة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0164',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Dreamy night - 6 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Lovely Brown',
                'title_ar' => 'جميل براون',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0165',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Lovely Brown - 7 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Delicate hands',
                'title_ar' => 'أيدي حساسة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0166',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Delicate hands - 8 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Mandala',
                'title_ar' => 'ماندالا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0167',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Mandala - 9 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Luxury engraving',
                'title_ar' => 'نقش فاخر',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0168',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Luxury engraving - 10 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Elegant engraving',
                'title_ar' => 'نقش أنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0169',
                'category_id' => '1',
                'image' => '/templates_image/Henna/Henna - Elegant engraving - 11 .png',
                'filter_id' => '5',
            ],
            [
                'title' => 'Elegant Pattern',
                'title_ar' => 'نمط أنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0026',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Elegant Pattern - 1 .png',
            ],
            [
                'title' => 'Arabic Calligraphy',
                'title_ar' => 'الخط العربي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0027',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Arabic Calligraphy - 2 .png',
            ],
            [
                'title' => 'Arabic Letters',
                'title_ar' => 'الحروف العربية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0028',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Arabic Letters - 3 .png',
            ],
            [
                'title' => 'Lettering',
                'title_ar' => 'حروف',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0029',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Lettering - 4 .png',
            ],
            [
                'title' => 'Arabian art',
                'title_ar' => 'الفن العربي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0030',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Arabian art - 5 .png',
            ],
            [
                'title' => 'Islamic pattern',
                'title_ar' => 'النمط الإسلامي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0031',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Islamec pattern - 7 .png',
            ],
            [
                'title' => 'Floral Decoration',
                'title_ar' => 'زخرفة الأزهار',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0032',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Floral Decoration- 8 .png',
            ],
            [
                'title' => 'Confident navy blue',
                'title_ar' => 'ثقة باللون الأزرق الداكن',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0033',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Confident navy blue - 9 .png',
            ],
            [
                'title' => 'Luxurious Technology',
                'title_ar' => 'التكنولوجيا الفاخرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0034',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Luxurious Technology - 10 .png',
            ],
            [
                'title' => 'Technology',
                'title_ar' => 'تكنولوجيا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0116',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Technology - 11 .png',
            ],
            [
                'title' => 'Luxury decoration',
                'title_ar' => 'زخرفة فاخرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0117',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Luxury decoration - 12 .png',
            ],
            [
                'title' => 'Elegant Mandala',
                'title_ar' => 'ماندالا الأنيقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0118',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Elegant Mandala -13 .png',
            ],
            [
                'title' => 'Gold flowers',
                'title_ar' => 'زهور ذهبية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0119',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - gold flowers - 14 .png',
            ],
            [
                'title' => 'Arabian Pattern',
                'title_ar' => 'النمط العربي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0120',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Arabian Pattern - 15 .png',
            ],
            [
                'title' => 'Elegant Glitter',
                'title_ar' => 'بريق أنيق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0121',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Elegant Glitter - 16 .png',
            ],
            [
                'title' => 'Stylish watercolor',
                'title_ar' => 'ألوان مائية أنيقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0122',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Stylish watercolor - 17 .png',
            ],
            [
                'title' => 'Luxurious golden leaves',
                'title_ar' => 'أوراق ذهبية فاخرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0123',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Luxurious golden leaves  - 18 .png',
            ],
            [
                'title' => 'Mysterious flowers',
                'title_ar' => 'زهور غامضة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0124',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Mysterious flowers - 19 .png',
            ],
            [
                'title' => 'Tulip',
                'title_ar' => 'توليب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0125',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Tulip - 21 .png',
            ],
            [
                'title' => 'Elegance',
                'title_ar' => 'أناقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0126',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Elegance - 22 .png',
            ],
            [
                'title' => 'Pink leaf',
                'title_ar' => 'ورقة وردية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0127',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Pink leaf - 24 .png',
            ],
            [
                'title' => 'Silk rose',
                'title_ar' => 'وردة الحرير',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0128',
                'category_id' => '2',
                'image' => '/templates_image/Business/Business - Silk rose - 25 .png',
            ],
            [
                'title' => 'Revival',
                'title_ar' => 'إحياء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0035',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Revival - 1 .png',
            ],
            [
                'title' => 'Pastel Pink',
                'title_ar' => 'الباستيل الوردي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0036',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Pastel Pink - 2 .png',
            ],
            [
                'title' => 'Merlot',
                'title_ar' => 'ميرلوت',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0037',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Merlot - 3 .png',
            ],
            [
                'title' => 'Watercolor Love',
                'title_ar' => 'الحب بالألوان المائية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0038',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Watercolor Love - 4 .png',
            ],
            [
                'title' => 'Puce',
                'title_ar' => 'رقاقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0039',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Puce - 5 .png',
            ],
            [
                'title' => 'Turkish roze',
                'title_ar' => 'روز تركي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0040',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Turkish roze - 6 .png',
            ],
            [
                'title' => 'Happy Day',
                'title_ar' => 'يوم سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0041',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Happy Day - 7.png',
            ],
            [
                'title' => 'Tales',
                'title_ar' => 'حكايات',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0042',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Tales - 8.png',
            ],
            [
                'title' => 'Whisper',
                'title_ar' => 'همسة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0043',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - Whisper - 9 .png',
            ],
            [
                'title' => 'a whisper of love',
                'title_ar' => 'همسة حب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0044',
                'category_id' => '3',
                'image' => '/templates_image/Save the date/Save the date - a whisper of love - 10.png',
            ],
            [
                'title' => 'cute illustrations',
                'title_ar' => 'الرسوم التوضيحية لطيف',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0045',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - cute illustrations - 1 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'cute flowers',
                'title_ar' => 'زهور لطيفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0046',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - cute flowers - 2 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'watercolor leaf illustrations',
                'title_ar' => 'الرسوم التوضيحية أوراق الألوان المائية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0047',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - watercolor leaf illustrations - 3 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Vector leaves',
                'title_ar' => 'أوراق المتجهات',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0048',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Vector leaves - 4 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Snowy day',
                'title_ar' => 'يوم مثلج',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0049',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Snowy day - 5 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Autumn butterflies',
                'title_ar' => 'فراشات الخريف',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0050',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Autumn butterflies - 7 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Simple illustrations',
                'title_ar' => 'الرسوم التوضيحية البسيطة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0051',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Simple illustrations - 8 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Happy flowers Vector',
                'title_ar' => 'ناقل الزهور السعيدة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0052',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Happy flowers Vector  -9 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Green beautiful leaf',
                'title_ar' => 'ورقة خضراء جميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0053',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Aqiqah/Aqiqah - Green beautiful leaf  -10 .png',
                'filter_id' => '6',
            ],
            [
                'title' => 'Red flowers',
                'title_ar' => 'الزهور الحمراء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0054',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - Red flowers - 1 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'Lovely silk flowers',
                'title_ar' => 'زهور الحرير الجميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0055',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - Lovely silk flowers - 2 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'ELegant gold and deep blue',
                'title_ar' => 'ذهبي أنيق وأزرق غامق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0056',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - ELegant gold and deep blue - 3 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'Beautiful floral ornaments',
                'title_ar' => 'الحلي الزهرية الجميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0057',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - beautiful floral ornaments - 4 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'lively Purple',
                'title_ar' => 'الأرجواني النابض بالحياة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0058',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - lively Purple - 5 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'lively rose',
                'title_ar' => 'ارتفع حية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0059',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - lively rose - 5 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'violet',
                'title_ar' => 'البنفسجي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0060',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - violet - 6 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'Pearls and flowers',
                'title_ar' => 'اللؤلؤ والزهور',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0061',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - Pearls and flowers  - 7.png',
                'filter_id' => '7',
            ],
            [
                'title' => 'Lovely olive green',
                'title_ar' => 'زيتون أخضر جميل',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0062',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - Lovely olive green  - 8.png',
                'filter_id' => '7',
            ],
            [
                'title' => 'lively Pine green',
                'title_ar' => 'الصنوبر الأخضر النابض بالحياة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0063',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Retirement/Retirement - lively Pine green -9 .png',
                'filter_id' => '7',
            ],
            [
                'title' => 'Magnolia',
                'title_ar' => 'ماغنوليا',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0064',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - Magnolia - 1.png',
                'filter_id' => '8',
            ],
            [
                'title' => 'Lvly flowers and roses',
                'title_ar' => 'زهور وورود لفلي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0065',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - Livly flowers and roses -3 .png',
                'filter_id' => '8',
            ],
            [
                'title' => 'pink and white roses',
                'title_ar' => 'الورود الوردية والبيضاء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0066',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - pink and white roses - 4.png',
                'filter_id' => '8',
            ],
            [
                'title' => 'branches',
                'title_ar' => 'الفروع',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0067',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - branches - 5.png',
                'filter_id' => '8',
            ],
            [
                'title' => 'Simple floral ornament',
                'title_ar' => 'زخرفة نباتية بسيطة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0068',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - Simple floral ornament - 6 .png',
                'filter_id' => '8',
            ],
            [
                'title' => 'Geometric flowers',
                'title_ar' => 'زهور هندسية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0069',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - Geometric flowers - 8 png.png',
                'filter_id' => '8',
            ],
            [
                'title' => 'Simple spring floral',
                'title_ar' => 'زهور الربيع البسيطة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0070',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Teacher Day/Teacher Day - Simple spring floral - 9 .png',
                'filter_id' => '8',
            ],
            [
                'title' => 'Fresh and elegant',
                'title_ar' => 'طازجة وأنيقة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0091',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Fresh and elegant - 1.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Black and gold',
                'title_ar' => 'الأسود والذهب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0092',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Black and gold - 2.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Luxurious silver',
                'title_ar' => 'فضية فاخرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0093',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Luxurious silver - 3.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Glow and beautiful',
                'title_ar' => 'توهج وجميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0094',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Glow and beautiful - 4.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'happy gold',
                'title_ar' => 'ذهب سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0095',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - happy gold - 5.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Textured Ornaments',
                'title_ar' => 'الحلي محكم',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0096',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Textured Ornamnets - 6.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Green and gold',
                'title_ar' => 'الأخضر والذهبي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0097',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Green and gold - 7.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Orange and blue',
                'title_ar' => 'البرتقالي والأزرق',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0098',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - Orange and blue - 8.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Colored Ornaments',
                'title_ar' => 'الحلي الملونة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0099',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha - colored Ornamnets - 9.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Simple green ornaments',
                'title_ar' => 'زخارف خضراء بسيطة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0100',
                'category_id' => '4',
                'image' => '/templates_image/Social Events/Eid al-Adha/Eid al-Adha -Simple green ornaments - 10.png',
                'filter_id' => '11',
            ],
            [
                'title' => 'Secret Garden',
                'title_ar' => 'الحديقة السرية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0071',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Secret Garden - 1 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Watercolor',
                'title_ar' => 'ألوان مائية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0072',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Watercolor - 2 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Sky',
                'title_ar' => 'سماء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0073',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Sky - 3.png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Bunny',
                'title_ar' => 'الأرنب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0074',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Bunny - 4 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Goose',
                'title_ar' => 'أوزة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0075',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Goose - 5 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Adventure',
                'title_ar' => 'مفامرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0076',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Adventure- 6 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Winter',
                'title_ar' => 'شتاء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0077',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Winter - 7 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Birds',
                'title_ar' => 'الطيور',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0078',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Birds - 8 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Happy Birds',
                'title_ar' => 'الطيور السعيدة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0079',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Happy Birds - 9.png',
                'filter_id' => '9',
            ],
            [
                'title' => 'Girl',
                'title_ar' => 'بنت',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0080',
                'category_id' => '5',
                'image' => '/templates_image/Baby/New Baby/New Baby - Girl - 10 .png',
                'filter_id' => '9',
            ],
            [
                'title' => 'lovely Whales',
                'title_ar' => 'الحيتان الجميلة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0081',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - lovely Whales - 1 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Happy Stork',
                'title_ar' => 'اللقلق سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0082',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Happy Stork - 2 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Cute Balloons',
                'title_ar' => 'بالونات لطيفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0083',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Cute Balloons - 3.png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Vintage',
                'title_ar' => 'كلاسيكي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0084',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Vintage - 4 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Cute Clothes',
                'title_ar' => 'ثياب لطيفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0085',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Cute Clothes - 5 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Happy flying',
                'title_ar' => 'طيران سعيد',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0086',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Happy flying - 6 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Angel',
                'title_ar' => 'ملاك',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0087',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Angel - 7 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Cute Animals',
                'title_ar' => 'حيوانات لطيفة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0088',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Cute Animals - 8 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Twin',
                'title_ar' => 'التوأم',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0089',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Twin - 9 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Flower Child',
                'title_ar' => 'إبن الزهرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0090',
                'category_id' => '5',
                'image' => '/templates_image/Baby/Baby Shower/Baby Shower - Flower Child - 10 .png',
                'filter_id' => '10',
            ],
            [
                'title' => 'Minimal',
                'title_ar' => 'الحد الأدنى',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0101',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Minimal - 1.png',
            ],
            [
                'title' => 'Islamic Ornament',
                'title_ar' => 'زخرفة إسلامية',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0102',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Islamic Ornament - 2.png',
            ],
            [
                'title' => 'Low poly',
                'title_ar' => 'بولي منخفض',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0103',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Low poly - 3.png',
            ],
            [
                'title' => 'Illustration',
                'title_ar' => 'توضيح',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0104',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Illustration - 4.png',
            ],
            [
                'title' => 'Geometric',
                'title_ar' => 'هندسي',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0105',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Geometric - 5.png',
            ],
            [
                'title' => 'Warm',
                'title_ar' => 'دافيء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0106',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Warm - 6.png',
            ],
            [
                'title' => 'Books',
                'title_ar' => 'كتب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0107',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Books - 7.png',
            ],
            [
                'title' => 'Perseverance',
                'title_ar' => 'مثابرة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0108',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Perseverance - 8.png',
            ],
            [
                'title' => 'Glitter Pyramid',
                'title_ar' => 'الهرم اللامع',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0109',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Glitter Pyramid- 9.png',
            ],
            [
                'title' => 'Female',
                'title_ar' => 'أنثى',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0110',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Femal - 10.png',
            ],
            [
                'title' => 'Celebrate',
                'title_ar' => 'احتفل',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0111',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Celebrate - 11.png',
            ],
            [
                'title' => 'University',
                'title_ar' => 'جامعة',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0112',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - University - 12.png',
            ],
            [
                'title' => 'flowers and book',
                'title_ar' => 'الزهور والكتاب',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0113',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - flowers and book - 13 .png',
            ],
            [
                'title' => 'Blue rose',
                'title_ar' => 'وردة زرقاء',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0114',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Blue rose - 14 .png',
            ],
            [
                'title' => 'Master',
                'title_ar' => 'يتقن',
                'description' => 'Dark theme with Pink flower',
                'description_ar' => 'موضوع الظلام مع زهرة وردية',
                'template_code' => '0115',
                'category_id' => '8',
                'image' => '/templates_image/Graduation/Graduation - Master - 15 .png',
            ],
        ];

        foreach ($templates as $data) {
            $template = Template::create([
                'title' => $data['title'],
                'title_ar' => $data['title_ar'],
                'description' => $data['description'],
                'description_ar' => $data['description_ar'],
                'template_code' => $data['template_code'],
                'category_id' => $data['category_id'],
                'image' => $data['image'],
            ]);

            if ($template && isset($data['filter_id'])) {
                FilterTemplate::create([
                    'template_id' => $template->id,
                    'filter_id' => $data['filter_id'],
                ]);
            }
        }

    }
}
